### PR TITLE
Revert "Ubuntu compatibility"

### PR DESCRIPTION
**Pull request by jp**
Reverts jp/ambari#6 @habelson is this PR broken ?

### CODE REVIEW

**Comment by habelson** [comment]
What was wrong with it?

**Comment by jp** [comment]
I was looking at your repo, and you reverted these changes on your side : https://github.com/habelson/chef-ambari/commit/75ca2e40fc843f1046f890e6b2ff7e7a069bf0d7

**Comment by jp** [comment]
If that's good for you I will merge it again and test it later.

**Comment by habelson** [comment]
I had reverted the changes out of my master in order to make a clean branch for the pull request. Sorry for the confusion

**Comment by jp** [comment]
No problem, you changes are merged. I'll push this on the supermarket tonight.

**Comment by habelson** [comment]
Just an FYI, did you happen to take a look at the other branch I’m working on where I’ve made the blueprint and cluster into LWRPs intstead of recipes? I probably don’t have the time to make it solid, but I wasn’t sure if you would be interested in what I did. It also includes no longer using curl.

**Comment by Joseph-R** [comment]
@habelson - I'm not sure where your changes are stored, but I would be interested in seeing them.

I may wrap them up and push them through, if that's something you are interested in.

Regards,
Joe Reid

**Comment by habelson** [comment]
https://github.com/habelson/chef-ambari/tree/blueprint-as-resource

Feel free to run with it if you like. Like I said it's probably not solid enough, but it might be a good start

**Pull request merged**
